export * from './edu.mock';
// export * from './teaching.mock';
export * from './events.mock';
export * from './planKPI.mock';
export * from './planRoutes.mock';
export * from './reports.mock';
export * from './routes.mock';
export * from './indicators.mock';
export * from './orders.mock';
export * from './deliveryPoints.mock';
export * from './qualities.mock';